# Generated by Django 5.2.4 on 2025-08-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='image',
        ),
    ]
